### ISSUE TITLE
Documentation for testing with Browser.Navigation.Key

### ISSUE THREAD

**Issue by jawspeak** [avh4/elm-program-test#112]
(I asked this in elm on slack but depending on when you read this the archive may be gone, https://elmlang.slack.com/archives/C192T0Q1E/p1595459807244000) 

We are trying to test where we use Browser.Nav.Key but the docs are unclear if this is supported or not.  What's the best practice for testing an app using a nav key? (We were thinking we should create an app, then navigate to another page, and assert it worked. Maybe this type of testing should be driven in the browser as automation, independent of elm?)

See these docs:
![image](https://user-images.githubusercontent.com/44742/88332202-09116980-cce3-11ea-9061-98c97affba93.png)

Of note we saw this PR https://github.com/avh4/elm-program-test/pull/94/files and this issue https://github.com/avh4/elm-program-test/issues/40 which are related to navigation.

However, I wonder if I'm thinking about it in the wrong way and instead of trying to generalize our functions using key as above we should use simulatedeffects or somehow sidestep the lack of a key in tests.

Asking another way...  what is the example update in the pic above trying to illustrate?
1) it can't suggest we change the update elm calls because we cannot overload the update : Msg -> Model -> ( Model, Cmd Msg ) that elm expects to call.
2) it can't imply we call from the existing update into that new update b/c elm does not support variable arg count as unique method signatures (can't overload update w/ another version w/ more args).
3) the code example above seems to suggest to build a fake pushUrl (a (key -> String -> Cmd msg) function, and then when Program Test uses a () for key, our fake can handle that but the real one couldn't. (?) 

I'm trying to decipher what the screenshot is actually saying to do.  I think it is this:
1. dependency inject a pushUrl, so you can pass in a fake/stub/mock in your test  
2. elm does not let you create a key in tests (it's protected elm core stuff and cannot be grabbed / monkey patched in other languages / accessed / etc - it's just impossible to create a key outside of receiving it from the elm runtime in the authorized way, so Program Test doesn't try to create one, it just passes in a ().
3. thus, make a fake pushUrl, and make it tolerate a () instead of a key, and then make assertions on that. (such as that pushUrl received such and such a url, ignoring the key)

also - is there a typo in the screenshot? See here:
![image](https://user-images.githubusercontent.com/44742/88332325-30683680-cce3-11ea-976a-61bb7c5844ef.png)

**Comment by avh4** [comment]
I just made a complete working example, see [NavigationKeyExample.elm](https://github.com/avh4/elm-program-test/blob/main/examples/src/NavigationKeyExample.elm) and [NavigationKeyExampleTest.elm](https://github.com/avh4/elm-program-test/blob/main/examples/tests/NavigationKeyExampleTest.elm).

Let me know if that helps or not.

**Comment by avh4** [comment]
The documentation was updated in #114 to point to the new examples.  If there's still difficulty here, please re-open, or create a new issue.
