### ISSUE TITLE
The HttpRequest type is not exported

### ISSUE THREAD

**Issue by allanderek** [avh4/elm-program-test#128]
A very minor issue. The functions:
```elm
expectHttpRequest :
    String
    -> String
    -> (HttpRequest msg msg -> Expectation)
    -> ProgramTest model msg effect
    -> Expectation
```
and
```elm
ensureHttpRequest :
    String
    -> String
    -> (HttpRequest msg msg -> Expectation)
    -> ProgramTest model msg effect
    -> ProgramTest model msg effect
```

Both take as argument a function of type: `HttpRequest msg msg -> Expectation`. However, the `HttpRequest` type is defined in the [SimulatedEffect](https://github.com/avh4/elm-program-test/blob/main/src/SimulatedEffect.elm#L28) module which is itself [not exported](https://github.com/avh4/elm-program-test/blob/main/elm.json#L7), and the `ProgramTest` module itself does not re-export it. So there is no way for a consumer of the library to refer to this type.

It's a minor issue because you can still **use** the functions, you just cannot type constrain that particular argument as in:

```elm
myTest : ProgramTest ...
myTest =
     let
           checkHttpRequest : SimulatedEffect.HttpResult -> Expectation -- CANNOT DO THIS.
           checkHttpRequest request =
                 Expect.equal """{"content":"updated!"}""") request.body
     in
     ...
        |> expectHttpRequest "POST" "https://example.com/save" checkHttpRequest
        ....
```

**Comment by avh4** [comment]
Ah yeah, I think it's a bug in elm-compiler that it allows you to publish a package that uses types that aren't exposed.  Definitely needs to be fixed here!

**Comment by allanderek** [comment]
Yeah I think that would be a nice additional feature to `elm publish`.
