### ISSUE TITLE
Support for asserting that a particular Http request has *not* been made

### ISSUE THREAD

**Issue by allanderek** [avh4/elm-program-test#132]
Just as the title states. The situation I have in which I would like this ability is the following:
- I have an app that periodically downloads data it needs to refresh
- When the browser window is `Hidden` the app skips the data refresh, but stores that it has skipped one, and then refreshes the data immediately if the visibility changes to `Visible`

The state machine for this is pretty simple, but nonetheless it would be good if this behaviour was covered by tests, especially as it isn't very observable eg. it's unlikely someone would report that the app is downloading data when the window is hidden.

Maybe I'm missing some generic way to say "expect this ProgramTest to have already accumulated this error".

**Comment by avh4** [comment]
Looks like this will become possible with the new API proposed in https://github.com/avh4/elm-program-test/issues/77#issuecomment-961611054

**Comment by avh4** [comment]
This can now be done in 3.6.0 https://package.elm-lang.org/packages/avh4/elm-program-test/3.6.0/ProgramTest#expectHttpRequests with

```
 |> ProgramTest.expectHttpRequests "GET" "https://example.com/api" (Expect.equal [])
```
