### ISSUE TITLE
Update elm-explorations/test dependency to >=2.0

### ISSUE THREAD

**Issue by khrynczenko** [avh4/elm-program-test#177]
We use latest `elm-program-test` in one of our projects together  with `elm-explorations/test ` and we would really like to upgrade  `elm-explorations/test` to version `2.1.0` since it now has features that we want to use. Unfortunately `elm-program-test` is not compatible with versions >=2.0. Is it possible to release new version compatible with >2.0 of `elm-explorations/test `?

**Comment by jfmengels** [comment]
This has been done and released in v4.0.0 👍
