### ISSUE TITLE
Naming of this package and types

### ISSUE THREAD

**Issue by avh4** [avh4/elm-program-test#5]
Currently, the main type in this package is called "`TestContext`".  Is that a good name?  Is there a better name?  (Other questions that may be related: is the package name "elm-program-test" a good one? Are the names of the exposed functions good ones?)

module/type name suggestions:

- `TestContext`
    - con: "whenever I'm gonna name something `Context` I try to find a more domain-specific name. (It's kinda one of those words like `Util` and `Misc`.)"
- `Execution`
    - con: "Execution" is an abstract concept which is also not commonly used during the course of Elm program development
- `Environment`
    - con: to some, this is a vague term.  More specifically, the "environment" typically means what's *around* the program that it interacts with, whereas this value includes the program itself
- `ProgramState`
    - con: "state" is perhaps not any more specific of a term than "context"
    - con: the value includes the program itself, in addition to the state
- `TestProgram`
    - con: to some, "Program" means the definition of the program, whereas this type represents both the program, and its state
- `TestResult`
    - con: not specific enough to this type of testing (other kinds of Elm tests would have "test results")
    - con: "result" implies a process has been completed, but this value is created and manipulated through the test (it is not simply created at the end)

**Comment by brookeangel** [comment]
Maybe "elm-browser-test" and `Test.Browser`, and `TestContext` becomes `Test.Browser.Program` ?

**Comment by avh4** [comment]
I think the winner here might be `ProgramTest` -- it matches the package name, avoids the cons listed above, and also sorts alphabetically above the other new modules in this package.
