### ISSUE TITLE
expectHttpRequestWasNotMade

### ISSUE THREAD

**Issue by Bernardoow** [avh4/elm-program-test#73]
Hi @avh4 !

My scenario is I have a form with some field and one button . One field is required and the button always is displayed.

1 Scenario -> Click on the button without filled the required field.

I Want do a test that I click on the button but the request is not made. Maybe it can be implemtend in your lib?!

**Comment by avh4** [comment]
The way to work around this in 3.1.0 would be to use something like this

```elm
...
    |> expectHttpRequestWasMade ...
    |> Test.Runner.getFailureReason
    |> Myabe.Extra.isJust
    |> Expect.equal True
```

**Comment by avh4** [comment]
This can now be done in 3.6.0 https://package.elm-lang.org/packages/avh4/elm-program-test/3.6.0/ProgramTest#expectHttpRequests with

```
 |> ProgramTest.expectHttpRequests "GET" "https://example.com/api" (Expect.equal [])
```
