### ISSUE TITLE
Handling repeat requests to same URL

### ISSUE THREAD

**Issue by mikeastock** [avh4/elm-program-test#77]
Hey! I've been trying to use elm-program-test to write tests on an app that uses graphql. One of the issues I've run into is simulating HTTP requests to the same URL doesn't seem to be supported. The use case for this is simulating multiple graphql queries for a given page.

```elm
all : Test
all =
    describe "Graphql Requests"
        [ test "multiple requests" <|
            \() ->
                start
                    |> ProgramTest.simulateHttpOk
                        "POST"
                        "https://example.com/graphql"
                        """{ "data": { "hello3832528868": "example" }}"""
                    |> ProgramTest.simulateHttpOk
                        "POST"
                        "https:/example.com/graphql"
                        """{ "data": { "today3832528868": "example" }}"""
                    |> ProgramTest.expectViewHas [ text "example", text "7" ]
        ]
```

A super simple workaround was to add a query param to the URL to make them unique but ideally, elm-program-test handles this internally.

What would you think about a contribution that used a hashed version of the simulated body to help uniquely identify each stored simulation?

**Comment by avh4** [comment]
I think allowing multiple requests is an important feature to add.  I some problems with the request body hashing are 1) that there is still a problem for testing an app that makes a request multiple times to the same URL with the same body, and 2) what would the API look like for letting the caller specify the expected body (which is solvable, but should be a clean API).  Also is there a change that could also allow people to check the headers of the request instead of the body?

I've been expecting that at some point the store of pending requests needs to be a multidict and store multiple requests to a given method/url.  I'm thinking maybe `simulateHttpResponse` should be changed to take a `HttpRequest -> Bool` function that could be used to check the body and/or the headers.

**Comment by mikeastock** [comment]
That totally makes sense. I would love to help out with this. Would you have time in the next couple of weeks to hop on a call to chat about how it should be architected?

**Comment by 7hoenix** [comment]
I know this hasn't been open for that long but am curious if we have had any movement on this?

**Comment by avh4** [comment]
Mike and I chatted about how to implement this -- not sure if he's had time to make any progress on it.

**Comment by avh4** [comment]
Working on this now, considering the following API for minor version release:

```elm
expectHttpRequestsWereMade : (method : String) -> (url : String) -> (expectedNumber : Int) -> ProgramTest -> Expectation

expectHttpRequests : (method : String) -> (url : String) -> (List Http.Request -> Expectation) -> ProgramTest -> Expectation

simulateHttpResponseAdvanced : (method : String) -> (url : String) -> (index : Int) -> Response String -> ProgramTest -> ProgramTest 
```

**Comment by avh4** [comment]
Added in 3.6.0 https://package.elm-lang.org/packages/avh4/elm-program-test/3.6.0/ :

Changes:

  - `expectHttpRequestWasMade`, `expectHttpRequest`, and `simulateHttpResponse` will now fail if multiple pending requests have been made to the relevant (method, URL) pair.

New features:

  - Added `expectHttpRequests` for checking whether multiple requests have been made to the same endpoint (or that zero requests have been made).
  - Added `simulateHttpResponseAdvanced` for simulating HTTP responses when multiple requests have been made to the same endpoint.


```elm
---- ProgramTest - MINOR ----

    Added:
        ensureHttpRequests :
            String.String
            -> String.String
            -> (List.List (Test.Http.HttpRequest msg msg) -> Expect.Expectation)
            -> ProgramTest.ProgramTest model msg effect
            -> ProgramTest.ProgramTest model msg effect
        expectHttpRequests :
            String.String
            -> String.String
            -> (List.List (Test.Http.HttpRequest msg msg) -> Expect.Expectation)
            -> ProgramTest.ProgramTest model msg effect
            -> Expect.Expectation
        simulateHttpResponseAdvanced :
            String.String
            -> String.String
            -> Basics.Int
            -> Http.Response String.String
            -> ProgramTest.ProgramTest model msg effect
            -> ProgramTest.ProgramTest model msg effect
```
